server:
  port: 9990
spring:
  data:
    mongodb:
      host: mongodb://root:password@localhost:27017/auth-demo?authSource=admin&authMechanism=MONGODB-CR
      database: auth-demo
      port: 27017
jwt:
  secret:
    key: 234lkj234jlk-13289y123hjkasd-123089123kas-123jasdjkasdjhhasjkd
