server:
  port: ${SERVER_PORT:9990}
spring:
  data:
    mongodb:
      host: mongodb://${DB_USERNAME:root}:${DB_PASSWORD:password}@${DB_HOST:localhost}/${DB_NAME:auth-prod}?authSource=admin&authMechanism=MONGODB-CR
      database: ${DB_NAME:auth-prod}
      port: ${DB_PORT:27017}

jwt:
  secret:
    key: 687fkj234jlk-13289y123hjkasd-123089123kas-123jasdjkasdjhhasjkd
