
#server:
#  port: 9999
spring:
  data:
    mongodb:
      host: mongodb://root:password@localhost:27017/auth-demo?authSource=admin&authMechanism=MONGODB-CR
      #host: mongodb://localhost:27017/auth-demo
      database: auth-demo
      port: 27017
      #username: root
      #password: password
      #authentication-database: auth-demo

jwt:
  secret:
    key: 234lkj234jlk-13289y123hjkasd-123089123kas-123jasdjkasdjhhasjkd
