server:
  port: 9990
spring:
  data:
    mongodb:
      host: mongodb://root:password@mongo-drmarkdown/auth-prod?authSource=admin&authMechanism=MONGODB-CR
      database: auth-prod
      port: 27017

jwt:
  secret:
    key: 687fkj234jlk-13289y123hjkasd-123089123kas-123jasdjkasdjhhasjkd
